version: '2'
services:
        nginx:
                container_name: my_nginx
                build: ./requirements/nginx
                restart: on-failure
                ports: 
                        - 443:443
                env_file:
                        - .env
                volumes:
                        - WP:/var/www/html
                networks:
                        - inception_nt
        wordpress:
                container_name: my_wordpress
                build: ./requirements/wordpress
                restart: on-failure
                env_file:
                        - .env
                volumes:
                        - WP:/var/www/html
                networks:
                        - inception_nt
        mariadb:
                container_name: my_mariadb
                build: ./requirements/mariadb
                restart: on-failure
                env_file:
                        - .env
                volumes:
                        - DB:/var/lib/mysql
                networks:
                        - inception_nt
volumes:
        DB:
                driver: local
                driver_opts:
                        type: none
                        o: bind
                        device: '/home/crisfern/data/DB'
        WP:
                driver: local
                driver_opts:
                        type: none
                        o: bind
                        device: '/home/crisfern/data/WP'
networks:
        inception_nt:
                name: inception_nt
